---
  access_token:
    description: "API access token"
    type: "string"
    secret: true
    required: true
  powershell_url:
    description: "The base URL used for O365 powershell commands execution"
    type: "string"
    secret: false
    required: false
    default: "https://cconsole.azurewebsites.net/api/HttpTriggerPowerShell1?code=zuzIeVijuKY1nt05/wgdT1Sr3LDS9XTfYTRrbB2yf/bErY8xrT18KA=="
